[Desktop Entry]
Name=AuraBrowser
Name[ca]=Navegador Aura
Name[cs]=AuraBrowser
Name[es]=AuraBrowser
Name[eu]=AuraBrowser
Name[fr]=AuraBrowser
Name[hi]=ओरा-ब्राउज़र
Name[it]=AuraBrowser
Name[nl]=AuraBrowser
Name[sk]=AuraBrowser
Name[sl]=AuraBrowser
Name[sv]=Aura webbläsare
Name[uk]=AuraBrowser
Name[x-test]=xxAuraBrowserxx
MimeType=@DesktopMimeType@
Exec=@DesktopExec@
Icon=aura-browser
Type=Application
NoDisplay=@DesktopNoDisplay@
GenericName=Aura Browser
GenericName[ca]=Navegador Aura
GenericName[cs]=Prohlížeč Aura
GenericName[es]=Navegador Aura
GenericName[eu]=Aura arakatzailea
GenericName[fr]=Navigateur Aura
GenericName[hi]=ओरा-ब्राउज़र
GenericName[it]=Aura Browser
GenericName[nl]=Aura-bladerprogramma
GenericName[sk]=Prehliadač Aura
GenericName[sl]=Brskalnik Aura
GenericName[sv]=Aura webbläsare
GenericName[uk]=Браузер Aura
GenericName[x-test]=xxAura Browserxx
Categories=Qt;KDE;Browser;Internet;
Keywords=program;software;Internet;
Keywords[ca]=programa;programari;Internet;
Keywords[cs]=program;software;Internet;
Keywords[es]=programa;software;Internet;
Keywords[eu]=programa;softwarea;Internet;
Keywords[fr]=programme ; logiciel ; Internet ;
Keywords[hi]=अनुप्रयोग;सॉफ्टवेयर;इंटरनेट;
Keywords[it]=programma;software;Internet;
Keywords[nl]=programma;software;internet;
Keywords[sk]=program;softvér;Internet;
Keywords[sl]=program;software;Internet;
Keywords[sv]=program;programvara;Internet;
Keywords[uk]=program;software;Internet;програма;інтернет;
Keywords[x-test]=xxprogramxx;xxsoftwarexx;xxInternetxx;
