[Desktop Entry]
Name=AuraBrowser
Name[ar]=متصفح أورا
Name[ca]=Navegador Aura
Name[ca@valencia]=Navegador Aura
Name[cs]=AuraBrowser
Name[de]=AuraBrowser
Name[en_GB]=AuraBrowser
Name[es]=AuraBrowser
Name[eu]=AuraBrowser
Name[fr]=AuraBrowser
Name[hi]=ओरा-ब्राउज़र
Name[hu]=AuraBrowser
Name[it]=AuraBrowser
Name[ko]=AuraBrowser
Name[nl]=AuraBrowser
Name[pl]=Przeglądarka Aura
Name[pt]=AuraBrowser
Name[ro]=AuraBrowser
Name[sk]=AuraBrowser
Name[sl]=AuraBrowser
Name[sv]=Aura webbläsare
Name[uk]=AuraBrowser
Name[x-test]=xxAuraBrowserxx
Name[zh_CN]=AuraBrowser
MimeType=@DesktopMimeType@
Exec=@DesktopExec@
Icon=aura-browser
Type=Application
NoDisplay=@DesktopNoDisplay@
GenericName=Aura Browser
GenericName[ar]=متصفح أورا
GenericName[ca]=Navegador Aura
GenericName[ca@valencia]=Navegador Aura
GenericName[cs]=Prohlížeč Aura
GenericName[de]=Aura Browser
GenericName[en_GB]=Aura Browser
GenericName[es]=Navegador Aura
GenericName[eu]=Aura arakatzailea
GenericName[fr]=Navigateur Aura
GenericName[hi]=ओरा-ब्राउज़र
GenericName[hu]=Aura böngésző
GenericName[it]=Aura Browser
GenericName[ko]=Aura 브라우저
GenericName[nl]=Aura-bladerprogramma
GenericName[pl]=Przeglądarka Aura
GenericName[pt]=Navegador Aura
GenericName[ro]=Navigator Aura
GenericName[sk]=Prehliadač Aura
GenericName[sl]=Brskalnik Aura
GenericName[sv]=Aura webbläsare
GenericName[uk]=Браузер Aura
GenericName[x-test]=xxAura Browserxx
GenericName[zh_CN]=光环浏览器
Categories=Qt;KDE;Browser;Internet;
Keywords=program;software;Internet;
Keywords[ar]=برنامج;تطبيق;إنترنت;
Keywords[ca]=programa;programari;Internet;
Keywords[ca@valencia]=programa;programari;Internet;
Keywords[cs]=program;software;Internet;
Keywords[de]=Browser
Keywords[en_GB]=program;software;Internet;
Keywords[es]=programa;software;Internet;
Keywords[eu]=programa;softwarea;Internet;
Keywords[fr]=Internet ;programme ; logiciel
Keywords[hi]=अनुप्रयोग;सॉफ्टवेयर;इंटरनेट;
Keywords[hu]=program;szoftver;Internet;
Keywords[it]=programma;software;Internet;
Keywords[ko]=program;software;Internet;프로그램;소프트웨어;인터넷;
Keywords[nl]=programma;software;internet;
Keywords[pl]=program;oprogramowanie;Internet;
Keywords[pt]=programa;aplicação;Internet;
Keywords[ro]=program;software;Internet;
Keywords[sk]=program;softvér;Internet;
Keywords[sl]=program;software;Internet;
Keywords[sv]=program;programvara;Internet;
Keywords[uk]=program;software;Internet;програма;інтернет;
Keywords[x-test]=xxprogramxx;xxsoftwarexx;xxInternetxx;
Keywords[zh_CN]=program;software;Internet;
